### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by behdad** [schani/linbin#3]
Hi,

Thanks for this project.  Would you please add a LICENSE file?  I'm experimenting with using SIMD to speedup bsearch() in HarfBuzz, and like to borrow your measurement infrastructure into HarfBuzz as I experiment.

https://github.com/harfbuzz/harfbuzz/issues/566

Thanks,
behdad

cc @ebraminio

**Comment by schani** [comment]
Do you prefer any particular license?  Would you mind sending a PR?

**Comment by behdad** [comment]
Thanks. I like "old MIT" or variants for their simplicity. Will send PR.

You also have me lots of ideas to experiment with. So far I implemented a 9ary search but have failed to see any speedup from it, so need to do proper benchmarking. But yeah didn't occur to me to combine that with a simd linear search.

**Comment by behdad** [comment]
Or there might be a point-and-click way for you on github website already...

**Comment by ebraminio** [comment]
Thanks for the nice work! Have a look at https://github.com/schani/linbin/community/license/new?branch=master&template=mit guess that should work, not sure if that is "old MIT", guess copying from https://github.com/harfbuzz/harfbuzz/blob/master/COPYING should work best also :)

**Comment by schani** [comment]
Wow, I didn't know GitHub had a UI for that! :-)

If you're interested in fast searching, you should read [this paper](http://arxiv.org/abs/1509.05053) which goes beyond what I did here.

**Comment by behdad** [comment]
Thanks!  Will read that paper.

Our workload involves very small datasets so a lot of research doesn't apply.
